# 필요한 데이터 준비

In [1]:
import pandas as pd
import numpy as np

In [2]:
거주인구=pd.read_csv("csv/거주인구 분석.csv")
카드소비량=pd.read_csv("csv/카드소비량 분석.csv")
유동인구=pd.read_csv("csv/유동인구 분석.csv")

In [3]:
거주인구

     emd_nm base_date      em_g  resid_reg_pop  foreign_pop  total_pop
0       건입동   2018-01  45646550         9800.0        228.0    10028.0
1       건입동   2018-02  42953550         9814.0        224.0    10038.0
2       건입동   2018-03  46422450         9783.0        222.0    10005.0
3       건입동   2018-04  42438700         9788.0        229.0    10017.0
4       건입동   2018-05  44893300         9800.0        238.0    10038.0
...     ...       ...       ...            ...          ...        ...
1629    효돈동   2021-02  26128400         5289.0         65.0     5354.0
1630    효돈동   2021-03  26845400         5262.0         61.0     5323.0
1631    효돈동   2021-04  25200200         5267.0         59.0     5326.0
1632    효돈동   2021-05  21724850         5266.0         60.0     5326.0
1633    효돈동   2021-06  27554100         5257.0         57.0     5314.0

[1634 rows x 6 columns]

In [4]:
카드소비량

,emd_nm,base_date,em_g,간식,농축수산물,마트/슈퍼마켓,배달,부페,식품,아시아음식,양식,주점및주류판매,패스트푸드,한식
0,건입동,2018-01,45646550,4540.0,1699.0,17547.0,585.0,55.0,5675.0,1961.0,1103.0,443.0,3430.0,20645.0
1,건입동,2018-02,42953550,3813.0,1857.0,15277.0,534.0,35.0,5133.0,1619.0,1028.0,371.0,3265.0,16989.0
2,건입동,2018-03,46422450,4531.0,1706.0,17327.0,714.0,25.0,6675.0,2303.0,1063.0,464.0,3865.0,21845.0
3,건입동,2018-04,42438700,4442.0,1821.0,18584.0,685.0,120.0,7334.0,2111.0,1141.0,455.0,3763.0,22796.0
4,건입동,2018-05,44893300,5044.0,2148.0,19218.0,719.0,110.0,8087.0,2472.0,1170.0,475.0,3839.0,24151.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1629,효돈동,2021-02,26128400,1256.0,921.0,7503.0,829.0,5.0,4057.0,678.0,210.0,95.0,1238.0,5726.0
1630,효돈동,2021-03,26845400,1362.0,1244.0,8631.0,946.0,0.0,4175.0,699.0,261.0,165.0,1343.0,7410.0
1631,효돈동,2021-04,25200200,1237.0,1181.0,8423.0,1130.0,0.0,4139.0,780.0,195.0,110.0,1192.0,7318.0
1632,효돈동,2021-05,21724850,1313.0,946.0,8659.0,1355.0,0.0,4297.0,645.0,220.0,145.0,1398.0,6265.0
1633,효돈동,2021-06,27554100,1135.0,940.0,8783.0,995.0,0.0,4219.0,720.0,225.0,105.0,1205.0,6258.0

In [5]:
유동인구

,emd_nm,base_date,em_g,내국인R,내국인W,내국인V,내국인관광W,내국인관광V,장기외국인R,장기외국인W,장기외국인V,단기외국인V
0,건입동,2018-01,45646550,6634.385743,853.143169,4394.226701,93.411009,2253.836991,163.093121,27.144504,184.660254,342.767185
1,건입동,2018-02,42953550,6792.429996,792.931207,4527.444740,72.605952,2086.436947,157.634191,25.059835,183.592907,407.349539
2,건입동,2018-03,46422450,6255.543504,844.365122,4492.754083,106.277464,1956.448967,157.744661,29.840575,179.973544,414.803235
3,건입동,2018-04,42438700,6147.776649,939.940213,4525.147147,90.625671,2200.409723,133.786537,23.023440,227.216227,492.573132
4,건입동,2018-05,44893300,6110.920450,911.932184,4673.567634,108.137345,2097.448691,158.017456,24.926140,184.512309,503.145429
...,...,...,...,...,...,...,...,...,...,...,...,...
1629,효돈동,2021-02,26128400,4067.873085,232.546457,1159.486708,25.547514,651.440943,107.642637,4.878595,55.161607,7.359677
1630,효돈동,2021-03,26845400,3820.298081,177.335442,1031.145764,27.071834,556.202510,95.738687,7.235740,59.334480,17.995356
1631,효돈동,2021-04,25200200,3798.216557,204.331082,986.355817,34.296987,669.338692,98.359823,6.412340,60.850661,16.514391
1632,효돈동,2021-05,21724850,3913.006223,177.050383,1005.330990,29.105367,685.551231,67.814038,3.943131,73.774356,14.754432
1633,효돈동,2021-06,27554100,3880.141514,172.792983,1028.800535,30.645732,661.193506,89.266496,5.234106,56.919068,6.959309

In [6]:
df=pd.merge(left=유동인구, right= 거주인구, how="left", on=["emd_nm","base_date","em_g"])
df=pd.merge(left=df, right= 카드소비량, how="left", on=["emd_nm","base_date","em_g"])
df

,emd_nm,base_date,em_g,내국인R,내국인W,내국인V,내국인관광W,내국인관광V,장기외국인R,장기외국인W,...,농축수산물,마트/슈퍼마켓,배달,부페,식품,아시아음식,양식,주점및주류판매,패스트푸드,한식
0,건입동,2018-01,45646550,6634.385743,853.143169,4394.226701,93.411009,2253.836991,163.093121,27.144504,...,1699.0,17547.0,585.0,55.0,5675.0,1961.0,1103.0,443.0,3430.0,20645.0
1,건입동,2018-02,42953550,6792.429996,792.931207,4527.444740,72.605952,2086.436947,157.634191,25.059835,...,1857.0,15277.0,534.0,35.0,5133.0,1619.0,1028.0,371.0,3265.0,16989.0
2,건입동,2018-03,46422450,6255.543504,844.365122,4492.754083,106.277464,1956.448967,157.744661,29.840575,...,1706.0,17327.0,714.0,25.0,6675.0,2303.0,1063.0,464.0,3865.0,21845.0
3,건입동,2018-04,42438700,6147.776649,939.940213,4525.147147,90.625671,2200.409723,133.786537,23.023440,...,1821.0,18584.0,685.0,120.0,7334.0,2111.0,1141.0,455.0,3763.0,22796.0
4,건입동,2018-05,44893300,6110.920450,911.932184,4673.567634,108.137345,2097.448691,158.017456,24.926140,...,2148.0,19218.0,719.0,110.0,8087.0,2472.0,1170.0,475.0,3839.0,24151.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1629,효돈동,2021-02,26128400,4067.873085,232.546457,1159.486708,25.547514,651.440943,107.642637,4.878595,...,921.0,7503.0,829.0,5.0,4057.0,678.0,210.0,95.0,1238.0,5726.0
1630,효돈동,2021-03,26845400,3820.298081,177.335442,1031.145764,27.071834,556.202510,95.738687,7.235740,...,1244.0,8631.0,946.0,0.0,4175.0,699.0,261.0,165.0,1343.0,7410.0
1631,효돈동,2021-04,25200200,3798.216557,204.331082,986.355817,34.296987,669.338692,98.359823,6.412340,...,1181.0,8423.0,1130.0,0.0,4139.0,780.0,195.0,110.0,1192.0,7318.0
1632,효돈동,2021-05,21724850,3913.006223,177.050383,1005.330990,29.105367,685.551231,67.814038,3.943131,...,946.0,8659.0,1355.0,0.0,4297.0,645.0,220.0,145.0,1398.0,6265.0
1633,효돈동,2021-06,27554100,3880.141514,172.792983,1028.800535,30.645732,661.193506,89.266496,5.234106,...,940.0,8783.0,995.0,0.0,4219.0,720.0,225.0,105.0,1205.0,6258.0

# 모델로 학습

## 데이터 준비

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

In [8]:
target = df['em_g']
data = df[df.drop(['em_g','emd_nm','base_date'],axis=1).columns]
data.shape, target.shape

((1634, 23), (1634,))

In [9]:
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=34)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1307, 23), (327, 23), (1307,), (327,))

In [10]:
poly = PolynomialFeatures(2) # 2~6차
poly_x = pd.DataFrame(poly.fit_transform(data.values), columns=poly.get_feature_names(data.columns))
x2_train, x2_test, y2_train, y2_test = train_test_split(poly_x, target, test_size=0.2, random_state=34)
print(x2_train.shape,x2_test.shape,y2_train.shape,y2_test.shape)

poly = PolynomialFeatures(3) # 2~6차
poly_x = pd.DataFrame(poly.fit_transform(data.values), columns=poly.get_feature_names(data.columns))
x3_train, x3_test, y3_train, y3_test = train_test_split(poly_x, target, test_size=0.2, random_state=34)
print(x3_train.shape,x3_test.shape,y3_train.shape,y3_test.shape)

poly = PolynomialFeatures(4) # 2~6차
poly_x = pd.DataFrame(poly.fit_transform(data.values), columns=poly.get_feature_names(data.columns))
x4_train, x4_test, y4_train, y4_test = train_test_split(poly_x, target, test_size=0.2, random_state=34)
print(x4_train.shape,x4_test.shape,y4_train.shape,y4_test.shape)

poly = PolynomialFeatures(5) # 2~6차
poly_x = pd.DataFrame(poly.fit_transform(data.values), columns=poly.get_feature_names(data.columns))
x5_train, x5_test, y5_train, y5_test = train_test_split(poly_x, target, test_size=0.2, random_state=34)
print(x5_train.shape,x5_test.shape,y5_train.shape,y5_test.shape)

poly = PolynomialFeatures(6) # 2~6차
poly_x = pd.DataFrame(poly.fit_transform(data.values), columns=poly.get_feature_names(data.columns))
x6_train, x6_test, y6_train, y6_test = train_test_split(poly_x, target, test_size=0.2, random_state=34)
print(x6_train.shape,x6_test.shape,y6_train.shape,y6_test.shape)

(1307, 300) (327, 300) (1307,) (327,)
(1307, 2600) (327, 2600) (1307,) (327,)
(1307, 17550) (327, 17550) (1307,) (327,)
(1307, 98280) (327, 98280) (1307,) (327,)
(1307, 475020) (327, 475020) (1307,) (327,)

## LR L1

In [11]:
model_L1 = Lasso(alpha=0.001, max_iter=1000, normalize=True)
model_L1.fit(x_train, y_train)
model_L2 = Lasso(alpha=0.001, max_iter=1000, normalize=True)
model_L2.fit(x2_train, y2_train)
model_L3 = Lasso(alpha=0.001, max_iter=1000, normalize=True)
model_L3.fit(x3_train, y3_train)
model_L4 = Lasso(alpha=0.001, max_iter=1000, normalize=True)
model_L4.fit(x4_train, y4_train)
model_L5 = Lasso(alpha=0.001, max_iter=1000, normalize=True)
model_L5.fit(x5_train, y5_train)
model_L6 = Lasso(alpha=0.001, max_iter=1000, normalize=True)
model_L6.fit(x6_train, y6_train)

C:\Users\HojunLee\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1.5704106902531264e+17, tolerance: 455988236796947.4
  model = cd_fast.enet_coordinate_descent(
C:\Users\HojunLee\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 5.757021834688165e+16, tolerance: 455988236796947.4
  model = cd_fast.enet_coordinate_descent(
C:\Users\HojunLee\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.942573726069867e+16, tolerance: 455988236796947.4
  model = cd_fast.enet_coordinate_descent(
C:\Users\HojunLee\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.246596580349824e+16, tolerance: 455988236796947.4
  model = cd_fast.enet_coordinate_descent(
C:\Users\HojunLee\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2.9093147677989708e+16, tolerance: 455988236796947.4
  model = cd_fast.enet_coordinate_descent(
C:\Users\HojunLee\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2.723529665307406e+16, tolerance: 455988236796947.4
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=0.001, normalize=True)

In [12]:
print(
model_L1.score(x_test,y_test),
model_L2.score(x2_test,y2_test),
model_L3.score(x3_test,y3_test),
model_L4.score(x4_test,y4_test),
model_L5.score(x5_test,y5_test),
model_L6.score(x6_test,y6_test),
sep="\n"
)

0.9187363844382845
0.9659182015727948
0.961367529323038
0.9410126910407879
0.8652947101773381
0.5915383978709452

## LR L2

In [13]:
model_R1 = Ridge(alpha=0.001, max_iter=1000, normalize=True)
model_R1.fit(x_train, y_train)
model_R2 = Ridge(alpha=0.001, max_iter=1000, normalize=True)
model_R2.fit(x2_train, y2_train)
model_R3 = Ridge(alpha=0.001, max_iter=1000, normalize=True)
model_R3.fit(x3_train, y3_train)
model_R4 = Ridge(alpha=0.001, max_iter=1000, normalize=True)
model_R4.fit(x4_train, y4_train)
model_R5 = Ridge(alpha=0.001, max_iter=1000, normalize=True)
model_R5.fit(x5_train, y5_train)
model_R6 = Ridge(alpha=0.001, max_iter=1000, normalize=True)
model_R6.fit(x6_train, y6_train)

Ridge(alpha=0.001, max_iter=1000, normalize=True)

In [14]:
print(
model_R1.score(x_test,y_test),
model_R2.score(x2_test,y2_test),
model_R3.score(x3_test,y3_test),
model_R4.score(x4_test,y4_test),
model_R5.score(x5_test,y5_test),
model_R6.score(x6_test,y6_test),
sep="\n"
)

0.9183241953866838
0.9677223953872743
0.9663507143161711
0.9301449704040371
0.770821127929262
0.10433409780824032

## Random Forest

In [15]:
model_randomForest = RandomForestRegressor() # 생성할 트리 개수가 얼만큼이 좋은지 모르겠음
model_randomForest.fit(x_train, y_train)
model_randomForest.score(x_test,y_test)

0.9725034688233066

In [16]:
sorted([(model_randomForest.feature_importances_[i], data.columns[i]) for i, v in enumerate(data.columns)], reverse=True)

[(0.3208384130943083, '간식'),
 (0.2736016461029244, '마트/슈퍼마켓'),
 (0.25423363197595567, '패스트푸드'),
 (0.04185486777774742, '한식'),
 (0.0206559566745793, 'total_pop'),
 (0.01272580331746323, '아시아음식'),
 (0.011213421944707638, 'resid_reg_pop'),
 (0.008946009275368826, '식품'),
 (0.006404344062658085, '양식'),
 (0.006344197906199055, '단기외국인V'),
 (0.0061985963622844704, 'foreign_pop'),
 (0.005769078605678708, '내국인V'),
 (0.005227493938924037, '내국인R'),
 (0.0050881535146363845, '농축수산물'),
 (0.004791295322004506, '내국인관광V'),
 (0.0030567463853037233, '내국인W'),
 (0.0028069115673819175, '내국인관광W'),
 (0.002400833023210648, '장기외국인V'),
 (0.0023462593644022734, '배달'),
 (0.0015831147511052614, '장기외국인R'),
 (0.001486203411942398, '주점및주류판매'),
 (0.0012939971483407829, '장기외국인W'),
 (0.0011330244728728445, '부페')]

# 저장

In [17]:
import joblib

In [18]:
joblib.dump(model_randomForest, '모델/총 분석_RF.pkl')

['모델/총 분석_RF.pkl']

In [19]:
df.to_csv("csv/총 분석.csv",  index=False)